import { StructuredDoc } from "./types";
import { taskOrientedDocs } from "./taskDocs.registry";
import { applyStructuredDocTemplate } from "./docTemplate";

const rawStructuredDocsRegistry: StructuredDoc[] = [
  {
    id: "getting_started",
    slug: "getting-started",
    categoryId: "quickstart",
    audience: "all",
    applicableVersion: "麦贝开源版 v0.1.0-preview+",
    applicableVersionEn: "MyBay Open Source v0.1.0-preview+",
    updatedAt: "2026-08-09",
    breadcrumbLabel: { "zh-CN": "快速上手", en: "Quick Start" },
    keywords: {
      "zh-CN": ["本地部署", "局域网", "服务器", "Docker", "Agent"],
      en: ["local deployment", "LAN", "server", "Docker", "Agent"]
    },
    content: {
      "zh-CN": {
        title: "快速上手麦贝开源版",
        summary: "使用本地管理员账号登录，选择正确的网络模式，并部署第一个可对话的 Agent 实例。",
        sections: [
          {
            title: "第一步：启动控制面板",
            paragraphs: [
              "本机使用运行 ./quick-start.sh；局域网共享运行 ./quick-start.sh --lan <宿主机IPv4>；公网服务器运行 ./quick-start.sh --server。",
              "桌面模式默认打开 http://localhost:3000。局域网使用选定的宿主机 IP；服务器模式使用配置的 HTTPS 控制台域名。"
            ],
            callout: {
              type: "info",
              title: "本地管理员",
              text: "开源版没有公开注册和邮箱验证。请使用 .env 或 quick-start.sh 生成的本地管理员账号登录。"
            }
          },
          {
            title: "第二步：完成部署前检测",
            paragraphs: [
              "进入“新建实例”后，先完成 Preflight。它会检查 Docker Socket、存储、网络、内部路由密钥和当前部署模式。",
              "desktop 模式只允许本机访问；lan 模式使用指定 IPv4；server 模式要求 Traefik、真实域名、通配 DNS 和 HTTPS。"
            ]
          },
          {
            title: "第三步：配置并部署 Agent",
            paragraphs: [
              "选择 Agent 镜像和版本，配置模型供应商、模型、API Key、Web 或外部通讯渠道，以及需要的技能。",
              "CPU、内存、磁盘和实例数量是本地宿主机保护参数，不是云端计费配额。请根据机器容量调整。",
              "选择 Web 渠道时，Agent 的 8642 对话 API 必须就绪；启用 Dashboard 时还会检查 9119 Web 管理端。"
            ]
          },
          {
            title: "第四步：访问实例",
            paragraphs: [
              "部署成功后，可以进入对话工作台，或在启用 Dashboard 时打开 Agent Web 控制台。",
              ".localhost 地址只能在 Docker 宿主机访问。其他局域网设备需要 LAN 模式，公网访问需要 server 模式。",
              "切换部署模式后应重新部署已有实例，使端口、内部 URL 和网关标签同步更新。"
            ]
          }
        ]
      },
      en: {
        title: "Get Started with MyBay Open Source",
        summary: "Sign in as the local administrator, choose the correct network mode, and deploy your first chat-ready Agent.",
        sections: [
          {
            title: "Step 1: Start the Control Panel",
            paragraphs: [
              "Run ./quick-start.sh for desktop use, ./quick-start.sh --lan <host-ipv4> for LAN sharing, or ./quick-start.sh --server for a public server.",
              "Desktop mode opens http://localhost:3000. LAN mode uses the selected host IP, and server mode uses the configured HTTPS console hostname."
            ],
            callout: {
              type: "info",
              title: "Local Administrator",
              text: "The open-source edition has no public registration or email verification. Sign in with the local administrator configured in .env or generated by quick-start.sh."
            }
          },
          {
            title: "Step 2: Complete Preflight",
            paragraphs: [
              "The deployment preflight checks Docker Socket access, storage, networking, the internal-routing secret, and the selected deployment mode.",
              "Desktop mode is host-only, LAN mode uses one selected IPv4 address, and server mode requires Traefik, real domains, wildcard DNS, and HTTPS."
            ]
          },
          {
            title: "Step 3: Configure and Deploy an Agent",
            paragraphs: [
              "Choose the Agent image and version, model provider, model, API key, communication channels, and optional skills.",
              "CPU, memory, disk, and instance-count values are local host guards, not hosted billing quotas.",
              "The Web channel requires the Agent chat API on port 8642. Enabling Dashboard also requires the web service on port 9119."
            ]
          },
          {
            title: "Step 4: Access the Instance",
            paragraphs: [
              "After deployment, use the Chat Workspace or open the Agent web console when Dashboard is enabled.",
              ".localhost addresses work only on the Docker host. Other LAN clients require LAN mode, and public access requires server mode.",
              "Redeploy existing instances after changing deployment mode so ports, internal URLs, and gateway labels are regenerated."
            ]
          }
        ]
      }
    }
  },
  {
    id: "chat_workspace",
    slug: "chat-workspace",
    categoryId: "quickstart",
    audience: "all",
    applicableVersion: "麦贝开源版 v0.1.0-preview+",
    applicableVersionEn: "MyBay Open Source v0.1.0-preview+",
    updatedAt: "2026-08-09",
    breadcrumbLabel: { "zh-CN": "对话工作台", en: "Chat Workspace" },
    keywords: {
      "zh-CN": ["对话工作台", "任务步骤", "文件预览", "8642", "排障"],
      en: ["chat workspace", "tool progress", "file preview", "8642", "troubleshooting"]
    },
    content: {
      "zh-CN": {
        title: "对话工作台与任务运行",
        summary: "了解对话代理链路、运行过程卡片、生成文件和常见初始化错误。",
        sections: [
          {
            title: "通信与鉴权链路",
            paragraphs: [
              "浏览器先请求 MyBay 控制面板，控制面板验证本地管理员会话后，再通过 Docker 内网访问 Agent 的 8642 对话 API。",
              "浏览器不会直接获得 Agent API Key。服务器模式下，Agent 的动态宿主端口也不应直接暴露到公网。"
            ]
          },
          {
            title: "任务运行体验",
            paragraphs: [
              "工作台会隔离不同实例、会话和 runId，避免切换后旧 SSE 或轮询结果污染当前页面。",
              "任务卡片支持折叠、步骤状态、任务与步骤耗时、部分输出恢复，以及任务结束时自动收敛未结束步骤。",
              "Agent 返回的安全文件路径可以点击预览；任务在后台完成时可以发送页面通知。"
            ]
          },
          {
            title: "8642 与 9119",
            paragraphs: [
              "8642 是 Agent 对话 API，Web 渠道和内置工作台依赖它。",
              "9119 是可选的 Hermes Web Dashboard。Dashboard 正常不代表 8642 一定可对话，部署诊断会分别检查两条链路。"
            ]
          },
          {
            title: "初始化失败排查",
            paragraphs: [
              "出现 BEGIN_TURN_FAILED 时，先确认实例可对话并刷新或新建会话，再查看控制面板日志中的真实错误。",
              "检查 Agent 是否监听 8642、API_SERVER_ENABLED 是否为 true、内部路由密钥是否一致，以及模型凭据是否有效。",
              "修改网络模式、密钥或 Agent 环境变量后，重新部署实例再测试。"
            ]
          }
        ]
      },
      en: {
        title: "Chat Workspace and Task Runs",
        summary: "Understand the chat proxy, run progress, generated files, and common initialization failures.",
        sections: [
          {
            title: "Communication and Authentication",
            paragraphs: [
              "The browser calls the MyBay control panel. After validating the local administrator session, the server reaches the Agent chat API on port 8642 through the Docker network.",
              "The browser never receives the Agent API key. In server mode, dynamic Agent host ports should not be public."
            ]
          },
          {
            title: "Run Experience",
            paragraphs: [
              "The workspace isolates instance, conversation, generation, and run identifiers so stale SSE or polling results cannot update a newly selected view.",
              "Run cards support collapsing, step state, task and step timing, partial-output recovery, and terminal step convergence.",
              "Safe generated-file paths open previews, and completed background tasks can trigger a page notification."
            ]
          },
          {
            title: "Ports 8642 and 9119",
            paragraphs: [
              "Port 8642 serves the Agent chat API used by the Web channel and Chat Workspace.",
              "Port 9119 serves the optional Hermes Web Dashboard. A healthy Dashboard does not guarantee that chat is ready; diagnostics check both paths separately."
            ]
          },
          {
            title: "Initialization Failures",
            paragraphs: [
              "For BEGIN_TURN_FAILED, first confirm that the instance is chat-ready, then refresh or create a conversation and inspect the control-panel log for the underlying error.",
              "Check that the Agent listens on 8642, API_SERVER_ENABLED is true, internal routing secrets match, and model credentials are valid.",
              "Redeploy the instance after changing network mode, routing secrets, or Agent environment variables."
            ]
          }
        ]
      }
    }
  },
  ...taskOrientedDocs
];

export const structuredDocsRegistry: StructuredDoc[] = applyStructuredDocTemplate(rawStructuredDocsRegistry);

export const VALID_GUIDES = [
  "getting_started", "chat_workspace", "deploy_instance", "files_storage",
  "security_practices", "error_troubleshooting", "runtime_spec"
];

export function getStructuredDocById(id: string): StructuredDoc | undefined {
  return structuredDocsRegistry.find(doc => doc.id === id);
}
