export const ErrorCodes = {
  UNKNOWN: "UNKNOWN",
  MISSING_LOGIN_PARAMETERS: "MISSING_LOGIN_PARAMETERS",
  MISSING_SLUG: "MISSING_SLUG",
  ACCESS_PASSWORD_REQUIRED: "ACCESS_PASSWORD_REQUIRED",
  INSTANCE_NOT_FOUND: "INSTANCE_NOT_FOUND",
  INSTANCE_CONFIG_INVALID: "INSTANCE_CONFIG_INVALID",
  INVALID_INSTANCE_CREDENTIALS: "INVALID_INSTANCE_CREDENTIALS",
  INSTANCE_PASSWORD_UNAVAILABLE: "INSTANCE_PASSWORD_UNAVAILABLE",
  INSTANCE_AUTH_NOT_CONFIGURED: "INSTANCE_AUTH_NOT_CONFIGURED",
  INSTANCE_AUTH_CHAIN_NOT_READY: "INSTANCE_AUTH_CHAIN_NOT_READY",
  INSTANCE_SESSION_COOKIE_MISSING: "INSTANCE_SESSION_COOKIE_MISSING",
  INSTANCE_SESSION_BRIDGE_FAILED: "INSTANCE_SESSION_BRIDGE_FAILED",
  INSTANCE_SESSION_UNAUTHORIZED: "INSTANCE_SESSION_UNAUTHORIZED",
  INSTANCE_LOGIN_RATE_LIMITED: "INSTANCE_LOGIN_RATE_LIMITED",
  INSTANCE_NETWORK_NOT_READY: "INSTANCE_NETWORK_NOT_READY",
  INSTANCE_LOGIN_ENDPOINT_FAILED: "INSTANCE_LOGIN_ENDPOINT_FAILED",
  INSTANCE_LOGIN_INTERNAL_ERROR: "INSTANCE_LOGIN_INTERNAL_ERROR",
  INSTANCE_READINESS_INTERNAL_ERROR: "INSTANCE_READINESS_INTERNAL_ERROR",
  CREDENTIALS_LOAD_FAILED: "CREDENTIALS_LOAD_FAILED",
  CREDENTIAL_FIELDS_REQUIRED: "CREDENTIAL_FIELDS_REQUIRED",
  CREDENTIAL_SECRET_INVALID: "CREDENTIAL_SECRET_INVALID",
  CREDENTIAL_BASE_URL_UNSAFE: "CREDENTIAL_BASE_URL_UNSAFE",
  CREDENTIAL_CREATE_FAILED: "CREDENTIAL_CREATE_FAILED",
  CREDENTIAL_UPDATE_FAILED: "CREDENTIAL_UPDATE_FAILED",
  CREDENTIAL_DELETE_FAILED: "CREDENTIAL_DELETE_FAILED",
  CREDENTIAL_IN_USE: "CREDENTIAL_IN_USE",
  CREDENTIAL_RATE_LIMITED: "CREDENTIAL_RATE_LIMITED",
  INSTANCE_CHANNEL_MANAGE_FORBIDDEN: "INSTANCE_CHANNEL_MANAGE_FORBIDDEN",
  CHANNEL_ACCEPTANCE_REQUIRED: "CHANNEL_ACCEPTANCE_REQUIRED",
  CHANNEL_ACCEPTANCE_NOT_REQUIRED: "CHANNEL_ACCEPTANCE_NOT_REQUIRED",
  CHANNEL_NOT_CONNECTED: "CHANNEL_NOT_CONNECTED",
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];

const ERROR_CODE_VALUES = new Set<string>(Object.values(ErrorCodes));

export function isErrorCode(value: unknown): value is ErrorCode {
  return typeof value === "string" && ERROR_CODE_VALUES.has(value);
}

export function instanceReadinessReasonToErrorCode(reason: string): ErrorCode {
  switch (reason) {
    case "basic_auth_not_enabled": return ErrorCodes.INSTANCE_AUTH_NOT_CONFIGURED;
    case "missing_plain_instance_password": return ErrorCodes.INSTANCE_PASSWORD_UNAVAILABLE;
    case "invalid_config": return ErrorCodes.INSTANCE_CONFIG_INVALID;
    case "internal_error": return ErrorCodes.INSTANCE_READINESS_INTERNAL_ERROR;
    default: return ErrorCodes.INSTANCE_AUTH_CHAIN_NOT_READY;
  }
}

export function instanceBridgeReasonToErrorCode(reason: string): ErrorCode {
  switch (reason) {
    case "basic_auth_not_enabled": return ErrorCodes.INSTANCE_AUTH_NOT_CONFIGURED;
    case "invalid_credentials": return ErrorCodes.INVALID_INSTANCE_CREDENTIALS;
    case "missing_plain_instance_password": return ErrorCodes.INSTANCE_PASSWORD_UNAVAILABLE;
    case "missing_hermes_session_cookie": return ErrorCodes.INSTANCE_SESSION_COOKIE_MISSING;
    case "hermes_rate_limited": return ErrorCodes.INSTANCE_LOGIN_RATE_LIMITED;
    case "network_not_ready": return ErrorCodes.INSTANCE_NETWORK_NOT_READY;
    case "password_login_endpoint_failed": return ErrorCodes.INSTANCE_LOGIN_ENDPOINT_FAILED;
    case "internal_error": return ErrorCodes.INSTANCE_LOGIN_INTERNAL_ERROR;
    default: return ErrorCodes.INSTANCE_SESSION_BRIDGE_FAILED;
  }
}